from logging import Logger

from flywheel.models.acquisition_list_output import (
    AcquisitionListOutput as AcquisitionListOutput,
)
from flywheel.models.container_output import ContainerOutput as ContainerOutput

from flywheel_adaptor.flywheel_proxy import FlywheelProxy as FlywheelProxy

log: Logger

class FlywheelREDCapImageForm:
    def __init__(self, session: ContainerOutput, proxy: FlywheelProxy) -> None: ...
    def __getitem__(self, key): ...
    def __setitem__(self, key, item) -> None: ...
    def __len__(self) -> int: ...
    def __delitem__(self, key) -> None: ...
    def clear(self): ...
    def copy(self): ...
    def get(self, item): ...
    def has_key(self, k): ...
    def update(self, *args, **kwargs): ...
    def keys(self): ...
    def values(self): ...
    def items(self): ...
    def pop(self, *args): ...
    def __contains__(self, item) -> bool: ...
    def __iter__(self): ...
    all_types_variables_to_check: list[str]
