exclude = [
    "comanage",
    "templates"
]

line-length = 88
indent-width = 4

target-version = "py312"

[lint]
select = ["A", "B", "C90", "E", "F", "I", "RUF", "S", "SIM", "UP", "W", "COM818", "E402", "PLW0406", "SLF001"]
ignore = ["S101", "UP038", "UP046", "UP047"]

[lint.per-file-ignores]
# TODO: confirm that this was a yapf/ruff conflict
"common/src/python/curator/scheduling.py" = ["I001"]
"common/src/python/event_capture/visit_event_accumulator.py" = ["I001"]
"common/test/python/event_capture/test_visit_event_accumulator.py" = ["I001"]
"tests/*" = ["SLF001"]
"common/test/python/curator/test_scheduling_models.py" = ["S105"]