import flywheel
import typing as t

from dataclasses import dataclass, field
from flywheel.models.file_output import FileOutput
from pathlib import Path


@dataclass
class File:
    name: str
    parent_type: str
    modality: str = ...
    type: str = ...
    mimetype: str = ...
    classification: dict[str, list[str]] = field(default_factory=dict)
    tags: list[str] = field(default_factory=list)
    info: dict = field(default_factory=dict)
    parents: dict[str, str] = field(default_factory=dict)
    zip_member_count: int | None = ...
    version: int | None = ...
    file_id: str | None = ...
    size: int | None = ...
    parent_id: str | None = ...
    source: str = ...

    @classmethod
    def from_config(cls, file_: dict, context: t.Any) -> File:
        ...

    @classmethod
    def from_sdk(cls, file_: FileOutput, context: t.Any) -> File:
        ...

    @property
    def fw_path(self) -> str:
        ...

    @property
    def local_path(self) -> Path | None:
        ...

    @staticmethod
    def download_file_to_temp(file_: FileOutput) -> Path:
        ...

    def __del__(self) -> None:
        ...
