[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "nacc-common"
version = "1.2.5"
description = "NACC Data Platform utilities"
requires-python = ">=3.10"

