"""Authorization client library for the NACC Authorization API."""

from authorization.client import AuthorizationClient
from authorization.exceptions import (
    AuthorizationClientError,
    ConfigurationError,
    NotFoundError,
    ParseError,
    ServiceUnavailableError,
    UnexpectedError,
    ValidationError,
)
from authorization.factory import create_authorization_client
from authorization.models import (
    AuthorizationModelMetadata,
    BatchError,
    BatchOperation,
    BatchOperationModel,
    BatchRequestModel,
    BatchResult,
    ComputedRelationMetadata,
    ErrorResponse,
    GrantRequest,
    GrantResult,
    HealthResult,
    InheritanceSource,
    ParentCombination,
    ParentRelationship,
    ParentRelationshipModel,
    PermissionCheckRequest,
    PermissionCheckResponse,
    PermissionEntry,
    RelationMetadata,
    ResourceListItem,
    ResourceListResponse,
    ResourceObject,
    ResourceParents,
    RevokeRequest,
    RevokeResult,
    SetParentsRequestModel,
    StructuralRelationMetadata,
    TypeMetadata,
    UpdateResourceRequest,
    UpdateResourceResponse,
    UserPermissions,
    UserProfile,
    UserProfileList,
    UserProfileRequest,
    UserProfileSearchResponse,
)
from authorization.sigv4_transport import SigV4Transport
from authorization.transport import HttpResponse, HttpTransport

__all__ = [
    "AuthorizationClient",
    "AuthorizationClientError",
    "AuthorizationModelMetadata",
    "BatchError",
    "BatchOperation",
    "BatchOperationModel",
    "BatchRequestModel",
    "BatchResult",
    "ComputedRelationMetadata",
    "ConfigurationError",
    "ErrorResponse",
    "GrantRequest",
    "GrantResult",
    "HealthResult",
    "HttpResponse",
    "HttpTransport",
    "InheritanceSource",
    "NotFoundError",
    "ParentCombination",
    "ParentRelationship",
    "ParentRelationshipModel",
    "ParseError",
    "PermissionCheckRequest",
    "PermissionCheckResponse",
    "PermissionEntry",
    "RelationMetadata",
    "ResourceListItem",
    "ResourceListResponse",
    "ResourceObject",
    "ResourceParents",
    "RevokeRequest",
    "RevokeResult",
    "ServiceUnavailableError",
    "SetParentsRequestModel",
    "SigV4Transport",
    "StructuralRelationMetadata",
    "TypeMetadata",
    "UnexpectedError",
    "UpdateResourceRequest",
    "UpdateResourceResponse",
    "UserPermissions",
    "UserProfile",
    "UserProfileList",
    "UserProfileRequest",
    "UserProfileSearchResponse",
    "ValidationError",
    "create_authorization_client",
]
