class FieldNames:
    """Class to store frequently accessed field names."""

    NACCID = "naccid"
    MODULE = "module"
    PACKET = "packet"
    PTID = "ptid"
    ADCID = "adcid"
    MODE = "mode"
    VISITNUM = "visitnum"
    DATE_COLUMN = "visitdate"
    FORMVER = "formver"
    GUID = "guid"
    OLDADCID = "oldadcid"
    OLDPTID = "oldptid"
    ENRLFRM_DATE = "frmdate_enrl"
    ENRLFRM_INITL = "initials_enrl"
    NACCIDKWN = "naccidknwn"
    PREVENRL = "prevenrl"
    C2C2T = "rmmodec2c2t"
    ENRLTYPE = "enrltype"
    GUIDAVAIL = "guidavail"
    SEX = "sex"
    BIRTHSEX = "birthsex"
    NPSEX = "npsex"
    NPDAGE = "npdage"
