python_sources(name="coreapi",
               sources=["**/*.py"],
               dependencies=["comanage:coreapi_client"],
               skip_docformatter=True,
               skip_mypy=True,
               skip_ruff=True)
