---
name: CI gear/base

on:
  pull_request:
    paths:
      - 'requirements.txt'
      - 'python-default.lock'
      - '.github/workflows/python_reusable.yaml'
      - '.github/workflows/ci_pull_metadata.yaml'
      - 'gear/pull_metadata/**'
  workflow_dispatch:  # Allows to trigger the workflow manually in GitHub UI

jobs:
  ci-gear-{PACKAGE_NAME}:
    uses:
      ./.github/workflows/python_reusable.yml
    with:
      working-directory: gear/pull_metadata
    secrets: inherit"""
    )