---
name: CI libs/base

on:
  pull_request:
    paths:
      - 'requirements.txt'
      - 'python-default.lock'
      - '.github/workflows/python_reusable.yaml'
      - '.github/workflows/ci_user_management.yaml'
      - 'gear/user_management/**'
  workflow_dispatch:  # Allows to trigger the workflow manually in GitHub UI

jobs:
  ci-gear-{PACKAGE_NAME}:
    uses:
      ./.github/workflows/python_reusable.yml
    with:
      working-directory: gear/user_management
    secrets: inherit"""
    )